#ifndef LATTICEMODELIMPLEMENTATIONS_mcmc_method_HEADER_HPP
#define LATTICEMODELIMPLEMENTATIONS_mcmc_method_HEADER_HPP

#include <lattice_model_impl/mcmc_method/global_mcmc_method/global_update_header.hpp>
#include <lattice_model_impl/mcmc_method/local_mcmc_method/local_update_header.hpp>

#include <lattice_model_impl/mcmc_method/dummy_mcmc_method.hpp>

#endif //LATTICEMODELIMPLEMENTATIONS_mcmc_method_HEADER_HPP
