#ifndef LATTICEMODELIMPLEMENTATIONS_GLOBAL_UPDATE_HEADER_HPP
#define LATTICEMODELIMPLEMENTATIONS_GLOBAL_UPDATE_HEADER_HPP

#include <lattice_model_impl/mcmc_method/global_mcmc_method/global_update_formalisms/hybrid_monte_carlo.hpp>

#endif //LATTICEMODELIMPLEMENTATIONS_GLOBAL_UPDATE_HEADER_HPP
