//
// Created by adrian on 02.06.22.
//

#ifndef LATTICEMODELIMPLEMENTATIONS_ONE_LINK_HEADER_HPP
#define LATTICEMODELIMPLEMENTATIONS_ONE_LINK_HEADER_HPP

#include "site_models/onelink_su_3_model.hpp"


#endif //LATTICEMODELIMPLEMENTATIONS_ONE_LINK_HEADER_HPP
