#ifndef LATTICEMODELIMPLEMENTATIONS_UPDATE_DYNAMICS_HEADER_HPP
#define LATTICEMODELIMPLEMENTATIONS_UPDATE_DYNAMICS_HEADER_HPP

#include <lattice_model_impl/update_dynamics/lattice_update_dynamics/lattice_update_header.hpp>
#include <lattice_model_impl/update_dynamics/site_update_dynamics/site_update_header.hpp>

#include <lattice_model_impl/update_dynamics/dummy_update_dynamics.hpp>

#endif //LATTICEMODELIMPLEMENTATIONS_UPDATE_DYNAMICS_HEADER_HPP
