#ifndef LATTICEMODELIMPLEMENTATIONS_LINK_LATTICE_HEADER_HPP
#define LATTICEMODELIMPLEMENTATIONS_LINK_LATTICE_HEADER_HPP

#include <lattice_model_impl/link_lattice/link_lattice_models/u1_model.hpp>
#include <lattice_model_impl/link_lattice/link_lattice_models/su2_model.hpp>

#endif //LATTICEMODELIMPLEMENTATIONS_LINK_LATTICE_HEADER_HPP
