#ifndef LATTICEMODELIMPLEMENTATIONS_SITE_UPDATE_HEADER_HPP
#define LATTICEMODELIMPLEMENTATIONS_SITE_UPDATE_HEADER_HPP

// #include <lattice_model_impl/update_dynamics/site_update_dynamics/site_update_formalisms/memory_simple_update.hpp>
#include <lattice_model_impl/update_dynamics/site_update_dynamics/site_update_formalisms/simple_update.hpp>
#include <lattice_model_impl/update_dynamics/site_update_dynamics/site_update_formalisms/update_with_adpative_step_size.hpp>

#endif //LATTICEMODELIMPLEMENTATIONS_SITE_UPDATE_HEADER_HPP
